export { default as Home } from './index';
export { default as About } from './about';
export { default as Contact } from './contact';
// export { default as About } from './about';
// export { default as News } from './updates';
// export { default as NewsDetail } from './updatesDetail';
// export { default as Professionals } from './professionals';
// export { default as ProfessionalDetail } from './professionalDetail';
// export { default as Services } from './services';
// export { default as ServiceDetail } from './serviceDetail';
// export { default as Contact } from './contact';
// export { default as Clients } from './clients';
// export { default as Career } from './career';
export { default as NotFound } from './notFound';